Diagnostics:
  ClangTidy:
    Add: modernize-*
    Remove: [modernize-use-nodiscard, modernize-use-trailing-return-type]
    Add: bugprone-*
    Add: performance-*
    Add: readability-*
    Add: misc-*
    Add: llvm-*
