#!/usr/bin/env bash

# shellcheck disable=SC2016
PREVIEW_COMMAND='f() {
  set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}")
  [ $# -eq 0 ] || (
    git show --no-patch --color=always $1
    echo
    git show --stat --format="" --color=always $1 |
    while read line; do
      tput dim
      echo " $line" | sed "s/\x1B\[m/\x1B\[2m/g"
      tput sgr0
    done |
    tac | sed "1 a \ " | tac
  )
}; f {}'

ENTER_COMMAND='(grep -o "[a-f0-9]\{7\}" | head -1 |
  xargs -I % bash -ic "git-fuzzy-diff %^1 %") <<- "FZF-EOF"
  {}
  FZF-EOF'

git log --graph --color=always --format="%C(auto)%h %s%d " | \
  SHELL=bash fzf --no-sort --tiebreak=index \
    --preview "${PREVIEW_COMMAND}" --preview-window=top:30 \
    --color \
    --ansi \
    --bind "enter:execute:${ENTER_COMMAND}"
