#!/usr/bin/env bash

# Interactively search git logs searching through the contents of the log/diff
# rather than just using the summary/description.

git status >& /dev/null
if [ $? -eq 128 ]; then return; fi

sk \
  --ansi \
  -ic"git log --all --oneline --color -G\"{}\" $*" \
  --preview="[[ -n "{1}" ]] && git show --color -G {cq} {1} | rg  --colors=match:fg:blue --colors=line:style:intense --color=always --passthru {cq}" \
  --bind="ctrl-j:preview-down,ctrl-k:preview-up" | awk '{print $1}'
